name: task_management_app
description: A task management application with Firebase
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  firebase_core_web: ^2.10.10
  firebase_auth: ^4.15.3
  firebase_auth_web: ^5.8.13
  cloud_firestore: ^4.13.6
  provider: ^6.1.1
  cupertino_icons: ^1.0.2
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
